version: "3"

services:
  redis:
    image: redis:5.0.4
    container_name: cache
    ports:
      - 6379:6379
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ts-starter
  web:
    build: .
    restart: on-failure:3
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: dev
    links:
      - redis
    volumes:
      - ./:/usr/src/app
